### ISSUE TITLE
Replace `stormcloud` with `storm-cloud`

### ISSUE THREAD

**Issue by gargajit** [FifthTry/bling#22]
As discussed with @amitu, the component name `stormcloud` contains two separate words therefore there has to be a hyphen between `storm` and `cloud`.
Repository Name: bling/quote

**Comment by amitu** [comment]
@gargajit, @gsalunke please review the names of other components in this package as well. We do not combine two words into one without dash.

**Comment by gargajit** [comment]
The issue has been fixed. The name of the component `stormcloud` has been renamed to `storm-cloud`.
The changes are live.
URL: https://fifthtry.github.io/bling/quote/

**Comment by gsalunke** [comment]
@amitu 
Thank you for your feedback.
We have created a separate issue to fix all such component names where we used two words and not added `-` hyphen.

Issue:
https://github.com/FifthTry/bling/issues/24

**Comment by gsalunke** [comment]
> @gargajit, @gsalunke please review the names of other components in this package as well. We do not combine two words into one without dash.

@amitu 
Thank you for your feedback.
We have created a separate issue to fix all such component names where we used two words and not added `-` hyphen.

Issue:
https://github.com/FifthTry/bling/issues/24

**Comment by gsalunke** [comment]
> @gargajit, @gsalunke please review the names of other components in this package as well. We do not combine two words into one without dash.

@amitu 
Thank you for your feedback.
We have created a separate issue to fix all such component names where we used two words and not added `-` hyphen.

Issue:
https://github.com/FifthTry/bling/issues/24
